"""Module with Worker and RemoteWorker classes for calculations control. Instanses of this classes can be generated by the calculator class."""

__all__ = []


class Worker: # use write_file to write input
    """
        Сlass for managing CSS structure calculations. Contains methods for performing and then collecting calculations on the local computer.
    """
    
    
class RemoteWorker:
    """
        Сlass for managing CSS structure calculations. Contains methods for performing and then collecting calculations on the remote server.
    """
    